### ISSUE TITLE
Multiplayer out of sync.

### ISSUE THREAD

**Issue by Gugnonk** [soulrelic616/bfc1138.js#18]
Hello,

first of all I want to thank you for this insane good modification.
While singleplayer works fine without problems, mulitplayer isn't playable for me and a bunch of friends. We've tried space and land, space runs out of sync under a minute of gameplay and land battles works for about ~ 10 minutes, but then the same error.
Is this known yet, or is multiplayer not supported?

**Comment by soulrelic616** [comment]
Hi,

The mod currently does not support multiplayer... We intend to support it but I imagine getting it there might take some time.  We will keep everyone updated about this!

Thanks for your support.
