### ISSUE TITLE
indestructible Kyramud Class Frigate, Bug

### ISSUE THREAD

**Issue by SirWalkAlot** [soulrelic616/bfc1138.js#2]
I've made a video showcasing the problem with the Kyramud Class Frigate.
https://www.youtube.com/watch?v=05HDAhdMT3M&feature=youtu.be

Also, 
Would you mind taking a look at the Planets: Hoth and Coruscant.
The income were getting on this planets is just to much.
Controlling Hoth or Coruscant just leads to infinite money.

Keep up the good work guys i'm really enjoying the mod!

**Comment by jedicars** [comment]
Patch 1.01 should fix the economy on new galactic conquests, it doesn't fix old saves.

**Comment by soulrelic616** [comment]
As jedicars mentions, patch 1.01 should solve the economy issue. We will look into the Kyramud code!

**Comment by Ardus-Kaine** [comment]
The Kyramud is less so indestructible than it is miraculously gaining MASSIVE tanking abilities once it's down to its last 3 hardpoints (An Ion Cannon and 2 Laser Cannons), which are all indestructible. They can be taken down by that point, but it feels as if they absorb more damage than the Malevolence and Mandator can COMBINED before being able to be taken down conventionally. I believe most losses in Galactic Conquest of them are a result of it not being able to enter hyperspace with the rest of the fleet. when retreating.

I also took a look at the XML files for the frigate and its hardpoints. It's not related to hardpoint health, if it's targettable, or if those hardpoints are destroyable, as the 1st part matches the other similar hardpoints, while "<Is_Targetable>" and "<Is_Destroyable>" are both set to "Yes" for all hardpoints.

**Comment by soulrelic616** [comment]
Yeah I think its a bug with the model itself, I'll update the code and test later today.

**Comment by Ardus-Kaine** [comment]
I had a feeling it was a model issue... 
It should be a simple copy and paste into the corresponding folders when it's complete, correct?

**Comment by soulrelic616** [comment]
Yes indeed Ardus.

This has now been fixed and yeah it was a problem with the model.  As a provisional solutio we had to comment out some hardpoints for this ship.  It renders it weaker, but shouldn't affect the overall faction too much.

The fix will be out with the next patch.

A proper model change will have to come in the future.

**Comment by Ardus-Kaine** [comment]
Just for quick reference, which of the hardpoints are commented out? I can apply the fix myself.

**Comment by Ardus-Kaine** [comment]
12 of 18 hardpoints commented out?
