### ISSUE TITLE
AI is Non-Aggressive/ does not attack in Both Galactic conquest and skirmish Red:Bug:  Green:Help Wanted:

### ISSUE THREAD

**Issue by Criptid** [soulrelic616/bfc1138.js#20]
Ok I know this is a requiring issue but its really annoying and making the game not fun/playable the AI in both Empire/Rebellion and Republic/CIS are non-aggressive does not attack. I mean when I started the game before the first patch with the whole credit bug thing I was able to get enough credits to build up and a army to attack and i still have a crap ton of credits but the AI will not attack me or any of my planets nor will they upgrade anything and thats in both Galactic Conquest and Skirmish the just seem to sit there while I just upgrade and build. I tried the whole remove the Ai and Enum file but that just makes it worst as my game just crash and I get this message across my screen "There were perception parsing errors. See PerceptionErrors.txt for details." hint thats the message I get I don't know if anyone else gets that but I do and its not my computer I have a good computer if I didn't I wouldn't be able to play all the mods I have for Empire at war including this and I do like all of them but none of them have as many bugs. So please fix or help me solve this problem its really annoying. Lol I want to blow up ships and watch my ships duke it out with the enemy

**Comment by soulrelic616** [comment]
Hi There!

The present issue is already being looked at, please follow the link below:

https://github.com/soulrelic616/bfc1138.js/issues/3

We are still trying to find out what could be causing this problem!
