### ISSUE TITLE
Predator Class is completely useless. [Bug?]

### ISSUE THREAD

**Issue by Ardus-Kaine** [soulrelic616/bfc1138.js#22]
The Predator-Class Star Destroyer is probably by and far THE WEAKEST ship I've ever seen. It costs a little over 84% of a full-price ISD-II (Which costs 6800, but usually is 5200 if you manage to hold onto your planets), weighing in at 6000 credits, but it somehow manages to go up in smoke faster than anything I've seen. An ACCLAMATOR manages to last longer than the Predator, and that's when it's under even heavier enemy fire than the Star Destroyer. Venators can last longer than these things, and they're only about 2/3's the price. It's like the Predator's armor is made out of cardboard.

Then again, I might not be using them correctly, but how am I supposed to learn how to use them if they can't even last 20 seconds under fire from ONE enemy vessel?

I'd edit some of the values myself for it, but then I risk ruining the intended balance.

**Comment by soulrelic616** [comment]
Hi there,

This is intended, the predator is almost useless without a fighter escort. Main thing when deploying this unit is to have it guarded by some TIE's or even an ISD as the Predator Class does not spawn fighters on its own. the hangars were sacrificed to fit in missile launchers. Once the unit fully deploys its deadly against fighters (and I mean VERY deadly) but the side effects of firing so many missiles at once means the ship's engines are compromised, therefore mobility is affected.

Try not putting the Predators against other capital ships, they wont last long, instead keep them behind your first line and have them take down the fighters.

**Comment by Ardus-Kaine** [comment]
Thank you for telling me that. I likely wouldn't have figured that out otherwise. I can't seem to find any reference to it in Wookiepdia, though. Is it an original unit, or does it go by a different name in the EU?
