### ISSUE TITLE
Reinforcement Lag

### ISSUE THREAD

**Issue by Ardus-Kaine** [soulrelic616/bfc1138.js#25]
This might be an issue on my end, but when I'm in a space battle and try to drag in reinforcements of a ship type that has yet to enter the battle at all, the game freezes for a while as soon as I click on the unit's icon, and after some time (Around 10 seconds usually, when calling in normal-sized capital ships, such as the ISD, and up to 30-60 seconds when bringing in SSD's and other "super" class ships, such as the Malevolence), it the game screen responds again and lets me drag the unit onto the battlefield. It only applies for the first unit of that class to be brought in, while all the others thereafter are fine.

I can still move the cursor around and the music is unaffected. Overall, it's not debilitating as much as it is an annoyance.

**Comment by soulrelic616** [comment]
Not much we can do bout it, I'm afraid... it's just the game's engine making sense of all the higher poly models and specific settings they have been coded with. It's slightly annoying, but doesn't break the game.

**Comment by Ardus-Kaine** [comment]
It's alright. Like I said, it's only a minor disadvantage, one I can live with.
