### ISSUE TITLE
Orbital Bombardment Bug

### ISSUE THREAD

**Issue by jedicars** [soulrelic616/bfc1138.js#26]
I think this is a bug. The Republic and the Empire ship bombardment option will kill your own troops, if they're in the circle.

**Comment by Ardus-Kaine** [comment]
Happened either in Republic at War or Thrawn's Revenge, as well. Might have something to do with the XML's.

**Comment by soulrelic616** [comment]
It's friendly fire. Keeps the mod realistic as a bomb would affect everyone.
