### ISSUE TITLE
Tiny Tiny Question

### ISSUE THREAD

**Issue by BXCommando** [soulrelic616/bfc1138.js#30]
So every time a squad of clones lands on the battlefield, they arrive on an imperial shuttle. Is this a bug or do you have no way of changing it?

**Comment by semillaofchaos** [comment]
I think if all of the starting garrison dies in skirmish they are replaced i dont know for sure

**Comment by Bucman55** [comment]
I believe the Clone squads are set to use Imperial transports as their landing craft. This can be changed with a simple XML edit.

**Comment by BXCommando** [comment]
Are you going to do the XML edit in an update or am I able to do it?

**Comment by JakeGreen163** [comment]
We will do it in a update, but atm i am away with my family until after the new year so there wont be an update until sometime in January.

**Comment by BXCommando** [comment]
Oh alright. Happy holidays then.
