### ISSUE TITLE
 crash at the beginning of a ground attack .

### ISSUE THREAD

**Issue by Crakus64** [soulrelic616/bfc1138.js#32]
When a faction ( Empire or Rebel ) attack one of my planets, the game crash and return to the office .
( I have a normal version of the game patched . )
 Thank you

**Comment by Crakus64** [comment]
I read the solution on the post , except , sorry, I had not seen for unofficial patch of Disney. And I confirm , it works ground combat and space no longer crash .

**Comment by soulrelic616** [comment]
Great! Thanks for letting us know its working now!
