### ISSUE TITLE
Venator Pathing Question, Possible Bug

### ISSUE THREAD

**Issue by jedicars** [soulrelic616/bfc1138.js#4]
The pathing on the Venator has a tendency to go wonky. I'll tell it to go attack an enemy ship that's coming in from, let's say the right, and then the Venator will turn away from the enemy ship, exposing its engines and preventing most of its cannons from firing. Then it will just sit there, like nothing wrong. Sometimes it makes an incredibly wide turn, as though its trying to avoid an asteroid, to attack the selected target. I can get it to make sharper turns or go the way I wan't it to go if I use the waypoint system and mark a path. I'm not sure if that's a bug or if its part of the mod. But if it is part of the mod. Could the Venator be given a little more speed?

**Comment by JakeGreen163** [comment]
This sadly is a problem with the game itself and not our mod almost all the ships do this every now and than in the main game.

**Comment by soulrelic616** [comment]
As Jake says this seems to be a problem with the mod, We'll keep having a look if anything can be done. but will be closing the issue for the time being.
