### ISSUE TITLE
Phase 2 Trooper Legion Question/Bug

### ISSUE THREAD

**Issue by jedicars** [soulrelic616/bfc1138.js#7]
Are the P2 blue legion troopers supposed to take a long time to be deployed? All of the other clones deploy quickly, but P2 troopers slowly deploy. Also while building them in galactic conquest, the time it takes is nearly instant.

**Comment by JakeGreen163** [comment]
The reason they take so long to deploy is cause you can select each soldier without them being in 1 big squad of 4 or 5 but i did fix the build time in GC.
